CREATE TABLE Endereco (
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Logradouro VARCHAR(50) NOT NULL,
	Bairro VARCHAR(40) NOT NULL,
	Cidade VARCHAR(40) NOT NULL,
	Estado VARCHAR(40) NOT NULL
)

CREATE TABLE Cliente (
	Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Nome VARCHAR(30) NOT NULL,
	Idade INT NOT NULL,
	Cpf VARCHAR(11) NOT NULL,
	EnderecoId INT NOT NULL,
	FOREIGN KEY (EnderecoId) REFERENCES Endereco (Id) ON DELETE CASCADE
)